package zoo_mgmt;

public enum DragonType {
	ANTIPODEAN_OPALEYE,
	CHINESE_FIREBALL,
	COMMON_GREEN_WELSH,
	HEBRIDIAN_BLACK,
	HUNGARIAN_HORNTAIL,
	NORWEGIAN_RIDGEBACK,
	PERUVIAN_VIPERTOOTH,
	ROMANIAN_LONGHORN,
	SWEDISH_SHORT_SNOUT,
	UKRANIAN_IRONBELLY
}